### PR TITLE
Fixes for issues #73, #74, and #75

### PR DESCRIPTION
**Pull request by jackaranda**

### CODE REVIEW

**Comment by pagecp** [comment]
Maybe you could do a pull request excluding issue #73 , or do another one when issue #73 is addressed?

**Comment by pagecp** [comment]
@jackaranda Maybe you could do a pull request excluding issue #73  , or do another one when issue #73  is addressed?

**Comment by jackaranda** [comment]
Closing this one and will create a new one without the change to the RXXpTOT code

**Comment by pagecp** [comment]
Thanks!! I am back from holidays, when you have time you can create the new one.

**Comment by pagecp** [comment]
@jackaranda feel free to create a new pull request without the change to the RXXpTOT code

**Pull request closed without merging**
