### PR TITLE
Adapt to xclim 0.40

### PR DESCRIPTION
**Pull request by aulemahal**
### Pull Request to resolve #xxx
- [x] Unit tests cover the changes.
- [ ] These changes were tested on real data.
- [ ] The relevant documentation has been added or updated.
- [ ] A short description of the changes has been added to `doc/source/references/release_notes.rst`.

### Describe the changes you made
We will soon release xclim 0.40 in which there are some breaking changes for icclim:

- [x] One of them was brought by Ouranosinc/xclim#1236 where `PercentileDataArray` was deprecated. In this PR I simply ported the class to icclim. 

- [ ] Another is from Ouranosinc/xclim#1227 where the "hydro" unit context was deactivated by default. This was mainly used to convert between precipitation rate ( mm /d ) and flux (kg m-2 s-1). With additions from Ouranosinc/xclim#1206, if the inputs of the `convert_units_to` function have valid and compatible standard names, the conversion can still be made automatically, but without these CF attributes, the default is to raise an error. This can be avoided by passing `context='infer'` or `context='hydro'` to `convert_units_to`. With the latter, the rate-to-flux transformations are always possible, while the former only activates them when the standard name of the input refers to water.

I saw the tests failures on my side, but I didn't want to apply a patch without opinions from people here.

### CODE REVIEW

**Comment by bzah** [comment]
Hi Pascal and thanks for the PR!

For the test failure I think it complains because at the moment icclim sees the 2 PercentileDataArray classes, one still in xclim 0.39 (percentile_doy returns an instance of it) and the other you just added.
It would probably be sufficient and future proof to modify the test with: 
```
def test_build_percentile_threshold__from_file(self):
        doys = percentile_doy(self.data)
        doys = PercentileDataArray.from_da(doys) # <- Le fix
        doys.to_netcdf(path=self.IN_FILE_PATH)
        ...
```

As for the Hydro update, thanks for pointing it out, I didn't follow the discussion on that.
@pagecp should decide what should be the behavior of icclim, but I'm going to give my thoughts anyway:
I would be tempted to simply use `infer` because GenericIndicators make it impossible to know if we are in an hydro context or not.
We would also need to revert [this commit ](https://github.com/cerfacs-globc/icclim/pull/232/commits/bcc4ecee220cb786f8a6ce53ea6c503273697583) so that the conversion logic is in one place (xclim).

**Comment by pagecp** [comment]
Hi Abel and all!
Yes I agree with Abel about the behavior of icclim!

**Comment by bzah** [comment]
The CI is broken when the PR comes from a fork and not icclim main repository, I tried to implement a fix but without success: #250 
So as long as the unit tests are passing locally we should not block this PR from merging.

**Comment by bzah** [comment]
Closing this pr in favor of the https://github.com/cerfacs-globc/icclim/pull/251 to workaround the CI issue.
Beware, the branch [Ouranosinc:adapt-to-xclim0-40](https://github.com/Ouranosinc/icclim/tree/adapt-to-xclim0-40) on Ouranosinc could become desynchronized

**Pull request closed without merging**
