### PR TITLE
Adapt to xclim 0.40

### PR DESCRIPTION
**Pull request by bzah**
PR originally opened by @aulemahal on https://github.com/cerfacs-globc/icclim/pull/248
Reopened here to workaround the CI issue.

### Pull Request to resolve #xxx
- [x] Unit tests cover the changes.
- [ ] These changes were tested on real data.
- [ ] The relevant documentation has been added or updated.
- [x] A short description of the changes has been added to `doc/source/references/release_notes.rst`.

### Describe the changes you made
We will soon release xclim 0.40 in which there are some breaking changes for icclim:

- [x] One of them was brought by Ouranosinc/xclim#1236 where `PercentileDataArray` was deprecated. In this PR I simply ported the class to icclim. 

- [x] Another is from Ouranosinc/xclim#1227 where the "hydro" unit context was deactivated by default. This was mainly used to convert between precipitation rate ( mm /d ) and flux (kg m-2 s-1). With additions from Ouranosinc/xclim#1206, if the inputs of the `convert_units_to` function have valid and compatible standard names, the conversion can still be made automatically, but without these CF attributes, the default is to raise an error. This can be avoided by passing `context='infer'` or `context='hydro'` to `convert_units_to`. With the latter, the rate-to-flux transformations are always possible, while the former only activates them when the standard name of the input refers to water.
  --> **(Abel edit) We should use `infer`.**
- [x] (Abel edit) We should revert changes related to unit conversion of this commit: https://github.com/cerfacs-globc/icclim/pull/232/commits/bcc4ecee220cb786f8a6ce53ea6c503273697583

I saw the tests failures on my side, but I didn't want to apply a patch without opinions from people here.

### CODE REVIEW

**Comment by bzah** [comment]
Ready for review, it would be great you could have a look @pagecp

**Comment by pagecp** [comment]
> Ready for review, it would be great you could have a look @pagecp

I will take a look at it, Thanks for this PR!

**Comment by pagecp** [comment]
The PR is ok for me.

**Review by pagecp — APPROVED** [review]

**Comment by pagecp** [comment]
We should merge asap because when we install icclim with pip it installs xclim 0.40 and it breaks,

**Comment by bzah** [comment]
Merged!
Thanks @aulemahal for the initial PR and @pagecp for the review 🎉

**Pull request merged**
